on:
  workflow_dispatch:
name: update
jobs:
  verify:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Install dependencies
      run: npm ci
    - name: Main
      run: node index.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
